root: true

parserOptions:
  ecmaVersion: 2018
  sourceType: "module"

env:
  es2017: true
  browser: true

extends:
  "htmlacademy/vanilla"

rules:
  indent: ['error', 4]
  no-multi-spaces: ['error']
  no-console: "off"
